#!/usr/bin/python

from ipblocker import model
from ipblocker import fake_ciscolib
from ipblocker.config import config

from ipblocker.nullroute_manager import Manager

IP = config.get("nullrouter","ip")

def main():
    m = Manager(IP, model, fake_ciscolib)
    m.manage()

if __name__ == "__main__":
    main()
