#!/usr/bin/env python
import sys
import os

from ipblocker import block_ip, get_block_pending
from ipblocker.util import wakeup_backend

if len(sys.argv) != 4:
    print "Usage: %s ip comment duration" % sys.argv[0]
    sys.exit(1)

user = os.getenv("USER")

ip, comment,duration = sys.argv[1:]
duration = int(duration)
block_ip(ip=ip, who=user, comment=comment, duration=duration, flag_traffic=True)
if get_block_pending():
    wakeup_backend()

