#!/usr/bin/python

import ren_isac
import simplejson
from ipblocker import model, logger
from ipblocker.config import config

DURATION = 60*60*24

def block():
    username = config.get("ri","username")
    password = config.get("ri","password")

    bt = ren_isac.bottrack(username, password)
    logger.debug("Fetching IP list from ren-isac")
    all = bt.cncip()
    logger.debug("Got %d ips" % len(all))
    all_ips = set(r['ip'] for r in all)

    for b in model.get_all_that_should_be_blocked():
        if b.who == 'ren-isac' and b.ip not in all_ips:
            model.unblock_ip(b.ip)
            logger.info("DB-unblocking %s" % b.ip)

    for r in all:
        msg = simplejson.dumps(r)
        ip = r['ip']
        model.block_ip(ip=ip, who='ren-isac', comment=msg, duration=DURATION,flag_traffic=True)
        logger.debug("DB-blocking %s" % ip)

        

if __name__ == "__main__":
    block()
