#!/usr/bin/env python

from ipblocker import model

def get_counts():
    counts = {}
    for b in model.get_all_that_should_be_blocked():
        who = b.who.replace(":", "_").replace("-","_")
        counts[who] = counts.get(who,0) + 1
    data = sorted(counts.items())
    return data

def main():
    data = get_counts()
    for who, cnt in data:
        print "%s.value %s" % ( who, cnt )

def config():
    data = get_counts()
    names = [who for who,cnt in data]
    print """
graph_args --vertical-label Blocked Hosts
graph_title Hosts Blocked by IPBlocker
graph_category security
graph_info This graph shows the number of hosts blocked by IPBlocker
""".strip()
    print "graph_order %s" % " ".join(names)
    for who,cnt in data:
        print "%s.draw STACK" % who
        print "%s.label %s" % (who, who)


if __name__ == "__main__":
    import sys
    if sys.argv[1:] == ["config"]:
        config()
    else:
        main()
