#!/usr/bin/env python

from ipblocker import model
from ipblocker.config import config

from ipblocker.nullroute_manager import Manager
import warnings
warnings.simplefilter('ignore', DeprecationWarning)
import cisco
warnings.resetwarnings()

IP = config.get("nullrouter","ip")

def main():
    m = Manager(IP, model, cisco)
    m.manage()

if __name__ == "__main__":
    main()
