#!/usr/bin/env python
from ipblocker import model
import sys
import os
import csv

def main(output_file):
    seen = set()
    c = model.blocks.c
    data = model.blocks.select().order_by(c.entered.desc()).execute()

    nfn = output_file + '.new'
    f = open(nfn, 'w')
    w = csv.writer(f)

    w.writerow(('dstip', 'who','comment'))
    for b in data:
        if b.ip in seen: continue
        w.writerow((b.ip, b.who,b.comment[:100].decode('ascii','replace')))
        seen.add(b.ip)
        
    os.fsync(f.fileno())
    f.close()

    os.rename(nfn, output_file)

if __name__ == "__main__":
    from optparse import OptionParser
    parser = OptionParser(usage="usage: %prog [options] /path/to/lookup_table.csv")
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.print_help()
        sys.exit(1)

    fn = args[0]
    main(fn)
    model.disconnect()
