#!/usr/bin/python
from ipblocker import model

def show_all(verbose=False):
    for b in model.get_all_that_should_be_blocked():
        if verbose:
            print b.ip, b.who, b.entered.strftime("%Y-%m-%d"), repr(b.comment)[:60]
        else:
            print b.ip

def show_one(ip):
    b = model.get_blocked_ip(ip)
    if not b:
        return

    print 'blocked at', b.blocked, 'by', b.who
    print 'unblock at', b.unblock_at, b.unblock_at_relative

    print b.comment

if __name__ == "__main__":
    from optparse import OptionParser
    parser = OptionParser()
    parser.add_option("-v", "--verbose",  dest="verbose", action="store_true",
        help="show detailed block information",default=False)
    (options, args) = parser.parse_args()
    if args:
        for ip in args:
            show_one(ip)
    else:
        show_all(options.verbose)
