#!/usr/bin/python
from ipblocker import model
import sys
import os

def save(fn, s):
    nfn = fn + '.new'
    f = open(nfn, 'w')
    f.write(s)
    os.fsync(f.fileno())
    f.close()
    os.rename(nfn, fn)

def main(output_file):
    s = ''
    s += "host in ["
    for b in model.get_all_that_should_be_blocked():
        s+= b.ip + " "
    s += "]\n"
    save(output_file, s)
    model.engine.dispose()

if __name__ == "__main__":
    fn = sys.argv[1]
    main(fn)
