#!/usr/bin/python

from ipblocker import model

def unblock():
    unblock = {}
    for b in model.get_unblock_pending():
        unblock[b.ip] = b
        print 'unblock', b

    for b in unblock.values():
        b.set_unblocked()

def block():
    block = {}
    for b in model.get_block_pending():
        block[b.ip] = b
        print 'block', b

    for b in block.values():
        b.set_blocked()

def main():
    model.Session.clear()

    try:
        unblock()
    except Exception, e:
        print "error unblocking", e

    try:
        block()
    except Exception, e:
        print "error blocking", e


if __name__ == "__main__":
    main()
