#!/usr/bin/python
from ipblocker import model

print "Blocked"
for b in model.Block.get_blocked():
    print b.ip, b.unblock_at

print
print "Block Pending"
for b in model.Block.get_block_pending():
    print b.ip

print
print "UnBlock Pending"
for b in model.Block.get_unblock_pending():
    print b.ip
