#!/usr/bin/env python
from ipblocker import model

print "Blocked"
for b in model.get_blocked():
    print b.ip, b.unblock_at, b.unblock_at_relative

print
print "Block Pending"
for b in model.get_block_pending():
    print b.ip

print
print "UnBlock Pending"
for b in model.get_unblock_pending():
    print b.ip
